batch_size: 30
test_batch_size: 1000
epochs: 3
lr: 0.0001
seed: 1
log_interval: 100
data_dir: 'data/car_data/car_data'
no_cuda: False
scheduler:
  step_size: 4
  gamma: 0.1
wandb:
  project: "MLOps_project"
ddp:
  set_device: "LOCAL_RANK"
  process_group: "nccl"
