name: Evaluate Model

on:
  push:
    paths:
      - "models/**"  # Trigger when a new model is added/updated -- Change path when everything is functional!
  workflow_dispatch: # Allow manual trigger

jobs:
  evaluate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: test-env

      - name: Install Dependencies
        run: |
          conda create -n test-env python=${{ matrix.python-version }} pip -y
          conda run -n test-env python -m pip install --upgrade pip
          conda run -n test-env pip install pytest
          conda run -n test-env pip install -r requirements.txt

      - name: Pull Model from DVC
        run: dvc pull models/best_model.pth.dvc -r myremote

      - name: Run Model Evaluation
        run: python evaluate.py

      - name: Upload Evaluation Results
        uses: actions/upload-artifact@v3
        with:
          name: evaluation-results
          path: evaluation_results.txt
