name: Run Unit Tests

on:
  push:
    branches:
      - main  # Run tests when pushing to main branch
  pull_request:
    branches:
      - main  # Run tests for PRs to main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: test-env

      - name: Install dependencies
        run: |
          conda create -n test-env python=${{ matrix.python-version }} pip -y
          source activate test-env || conda activate test-env
          python -m pip install --upgrade pip
          pip install pytest thop wandb
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          conda activate test-env
          pytest tests/
          pytest --maxfail=5 --disable-warnings -v  # Run all tests with verbose output
